name: 'Build on macOS'

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to build folder
      run: cd build
    - name: Use CMake to make everything ready
      run: cmake ..
    - name: build
      run: cmake --build .
