name: 'Build on macOS'

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use CMake to make everything ready
      working-directory: ./build
      run: cmake ..
    
    - name: Compile
      working-directory: ./build
      run: cmake --build .
